### ISSUE TITLE
Checkpoints installation problem

### ISSUE THREAD

**Issue by michalwitek1232** [opendreamnet/dreampower#137]
I tried to install checkpoints downloaded from `http://download2391.mediafire.com/97qievn7plsg/5pz0l10njlpc86b/checkpoints.zip`

I extracteed it to `./checkpoints` folder, and when I run: `./dreampower.exe checkpoints -d` I'm getting this:
```
PS C:\Users\Michal\Desktop\dn> ./dreampower.exe checkpoints -d
Traceback (most recent call last):
  File "main.py", line 85, in <module>
  File "argv\__init__.py", line 35, in run
  File "checkpoints.py", line 19, in main
  File "checkpoints.py", line 19, in <listcomp>
  File "ntpath.py", line 78, in join
TypeError: expected str, bytes or os.PathLike object, not dict
[18796] Failed to execute script main
```

**Comment by Pingasmaster** [comment]
Try deleting everything (software, checkpoints...) and re-downloading from original mirror located at https://www.dreamtime.tech/docs/, you will also find step-by-step tutorials on how to install and use this software.

This is clearly an issue with the checkpoints you downloaded as the log mentions, however, if the issue persists, reply to me, alongside with enabling debug mode and the software log, your hardware configuration, and all other useful info you might have.

Hoping to have been useful, please close the issue if this comment solved your problem.
